### ISSUE TITLE
Rpmdb checksum issues

### ISSUE THREAD

**Issue by KurtStam** [resin-io/qemu#12]
When running any `yum -y install <package>`. I get

`Rpmdb checksum is invalid: dCDPT(pkg checksums): apr.aarch64 0:1.4.8-3.el7 - u`

The above error is specific to installing apr. The workaround is to use `yum -y install <package> --nogpgcheck. See my test project Dockerfile: 
https://hub.docker.com/r/kurtstam/aarch64-test-dockerhub
https://github.com/KurtStam/aarch64-test-dockerhub

I'm guessing there is code path that avoids going through qemu, so that the checksum fails.

Plz let me know what I can do to help debug and fix.

Cheers,

--Kurt

**Comment by petrosagg** [comment]
@KurtStam have you tried the building exact same Dockerfile on a `aarch64` but without the `[ "cross-build-start" ]` part to make sure it's because of QEMU?

**Comment by petrosagg** [comment]
Acutally, I just ran your test Dockerfile and it works. Maybe an issue with your network that modified the download the made the signature fail? I'm not sure. Closing for now but feel free to re-open if you see it's due to QEMU.

**Comment by KurtStam** [comment]
Hi @petrosagg Thx for looking at this. To answer your questions above:

1. Yes it runs fine on aarch64 (with the cross-build statements removed)

2. I'm still seeing the issue when running on my OSX and also on docker hub:
https://gist.github.com/KurtStam/c701735348d67929c33d5d212e9582fa
I would have reopened if I had that permission. 

--Kurt
