### ISSUE TITLE
getcpu(2) is not implemented

### ISSUE THREAD

**Issue by petrosagg** [resin-io/qemu#13]
ASP.NET programs print `qemu: Unsupported syscall: 345`

**Comment by usma0118** [comment]
facing same issue.
compiled dotnet app with -r linux-arm parameter.

**Comment by jabrena** [comment]
Any schedule to implement this method?
http://man7.org/linux/man-pages/man2/getcpu.2.html

For OpenJDK11 is necessary

**Comment by petrosagg** [comment]
I just published QEMU 3.0.0-rc4+resin that includes https://github.com/resin-io/qemu/commit/b827c3ed30e4777ab9bd91cb240252a4815b3322

You can find the binaries here https://github.com/resin-io/qemu/releases/tag/v3.0.0-rc4%2Bresin
