### ISSUE TITLE
Update to latest qemu?

### ISSUE THREAD

**Issue by breandan** [resin-io/qemu#16]
Most of the resin-io [Docker images](https://hub.docker.com/r/resin) contain an old qemu-arm-static binary. Now that ~qemu 3.0~ ~qemu 4.0~ ~qemu 4.1~ ~qemu 5.0~ ~qemu 5.1~ ~qemu 6.1~ [qemu 6.2 is released](https://wiki.qemu.org/ChangeLog/6.2), it would be nice to support it!

**Comment by breandan** [comment]
@petrosagg I tried updating the `qemu-arm-static` binary manually, but encountered the same issue described in [this 2016 comment](https://github.com/resin-io-playground/armv7hf-debian-qemu/issues/2#issuecomment-192662375):

```
...
Step 9/25 : COPY ./bin/ /usr/bin/
---> 2fa9e5cd570d
Step 10/25 : RUN [ "cross-build-start" ]
---> Running in a65b8242f164
/usr/bin/cross-build-start: 3: /usr/bin/cross-build-start: Cannot fork
```

Unsure how to proceed, as we need a more recent version of `qemu-arm-static` to support certain syscalls.

**Comment by CameronDiver** [comment]
@breandan We are currently working on upgrading to v4.0.0.

**Comment by guysoft** [comment]
Any news? Need help?

**Comment by CameronDiver** [comment]
Hey @guysoft sorry looks like we forgot to close this issue, we actually released 4.0.0 back then: https://github.com/balena-io/qemu/releases/tag/v4.0.0-balena


Unfortunately the github releasess are a bit strange, and order 4.0.0 fairly far back, and I couldn't work out why exactly.

In terms of 4.1, this isn't going to be a huge priority for us, but if you'd like to see it then we'd certainly try to help you achieve this.

**Comment by lurch** [comment]
> Unfortunately the github releasess are a bit strange, and order 4.0.0 fairly far back, and I couldn't work out why exactly.

https://github.com/balena-io/qemu/tags?after=v2.6.0-rc1 seems to think that v4.0.0-balena was tagged "on 11 Mar 2016" ?? :confused: 
... hmmm, maybe that's because that's the timestamp on the most recent commit on the balena-4.0.0
branch? https://github.com/balena-io/qemu/branches  (i.e. GH is using the commit-authoring date, whereas you'd want it to be using the commit-merging date?) :man_shrugging:

**Comment by CameronDiver** [comment]
Yeah that seems fairly likely. I guess we could just add a dummy commit to the end of the branch on the next upgrade to solve this.

**Comment by klutchell** [comment]
We are now running QEMU v6 in our base images as per https://github.com/balena-io-library/base-images/pull/715
