### ISSUE TITLE
Alpine Linux: Exec format on all but echo commands

### ISSUE THREAD

**Issue by marvinroger** [resin-io/qemu#5]
Hi,

I have the following Dockerfile:

```Dockerfile
FROM resin/armhf-alpine:3.4

RUN [ "qemu-arm-static", "/bin/sh", "-c", "echo lolipop" ]
RUN [ "qemu-arm-static", "/bin/sh", "-c", "cat /etc/alpine-release" ]
```

I've been trying to build this from Docker Hub, but [it fails](https://hub.docker.com/r/homiedashboard/mosquitto-armhf/builds/bkzsvxx7xbnzlyyu5sjzhaa/). The `echo` command works well, the `cat` fails with an `cat: Exec format error`.

**Comment by petrosagg** [comment]
Hey @marvinroger. You have to either pass the `-execve` flag to QEMU or add `ENV QEMU_EXECVE=1` in your Dockerfile to make this work. Your second command is attempting to run a child process and that's why it's failing
